#!/bin/sh
PAM_SUDO=/etc/pam.d/sudo
if grep pam_tid.so $PAM_SUDO > /dev/null
then
	echo pam_tid.so already present in $PAM_SUDO ✅
else
	echo Installing pam_tid.so in $PAM_SUDO 🆗
	sudo ex $PAM_SUDO <<eof
1 insert
auth sufficient pam_tid.so
.
xit
eof

fi
