[tools]
assh = "latest"
claude = "latest"
codex = "latest"
deno = "latest"
dotnet = "8"
gemini = "latest"
go = "latest"
htmlq = "latest"
java = "latest"
jq = "latest"
lua = "latest"
node = "latest"
perl = "latest"
python = "latest"
rust = "latest"
swiftformat = "latest"
swiftgen = "latest"
uv = "latest"

[env]

# https://mise.jdx.dev/configuration/settings.html
[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "node"]

[settings.python]
default_packages_file = "{{ get_env(name='XDG_CONFIG_HOME', default='~/.config') }}/python/default-python-packages"

[settings.ruby]
default_packages_file = "{{ get_env(name='XDG_CONFIG_HOME', default='~/.config') }}/ruby/default-gems"
