[tools]
assh = "latest"
dotnet = "8"
go = "latest"
java = "latest"
lua = "latest"
perl = "latest"
rust = "latest"
swiftformat = "latest"
swiftgen = "latest"
uv = "latest"

[tools.python]
version="latest"
postinstall="echo use link-xonsh to activate a newly installed xonsh"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "node"]
