[tools]
assh = "latest"
dotnet = "8"
gemini = "latest"
go = "latest"
java = "latest"
lua = "latest"
node = "latest"
perl = "latest"
python = "latest"
rust = "latest"
swiftformat = "latest"
swiftgen = "latest"
uv = "latest"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python", "ruby", "node"]
