#!/bin/sh
# The -launchAfterInstall parameter is pretty much straightforward. Omitting it will allow to install the apps silently.
grep -v '#' ~/.config/homebrew/Setappfile |  tr \\n \\0 | xargs -0 -p -J % /Applications/Setapp.app/Contents/MacOS/Setapp -installApps % "$*"
