#!/bin/sh

# Python
asdf plugin-add python
asdf install python latest 
asdf global python latest

# Ruby
asdf plugin-add ruby
asdf install ruby latest 
asdf global ruby latest

# Java
asdf plugin-add java
